name: my-hobby-page-front-workflow
on: [push]

jobs:
  build:
    name: deployment front server
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        users: actions/checkout@master
      